<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">
        <?= $user['firstName'] . '&nbsp;' . $user['lastName']?>
    </h1>

    <p>
    This could be for all your info etc
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank">
        Check Laminas on GitHub &raquo;
    </a>
</div>
<div class="card-deck">


	<?php 
	foreach ($friends as $friend):
	?>
	    <div class="card">
        <h2 class="card-header">
        	<?= $friend?>
        </h2>
        <div class="card-body">
            <p>
                
            </p>
            <a class="btn btn-primary" href="#" target="_blank">View <?= $friend?>'s Profile&raquo;</a>
        </div>
    	</div>
	<?php 
	endforeach;
	?>

  
</div>
