<link rel="stylesheet" href="css/styles.css">

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="fb-profile-block">
                <div class="fb-profile-block-thumb cover-container">
                
                <img src="<?= $this->user['coverImage']?>" width="1110" height="312" >
                
                </div>
                <div class="profile-img">
                    <a href="#">
                        <img src="<?= $this->user['profileImage']?>" alt="" title="">        
                    </a>
                </div>
                <div class="profile-name">
                    <h2>
                    <?= $this->user['firstName']; '&nbsp' . $this->user['lastName']?>
                    </h2>
                </div>
                
                <div class="fb-profile-block-menu">
                    <div class="block-menu">
                        <ul>
                            <li><a href="#">Timeline</a></li>
                            <li><a href="#">about</a></li>
                            <li><a href="#">Friends</a></li>
                            <li><a href="#">Photos</a></li>
                            <li><a href="#">More...</a></li>
                        </ul>
                    </div>
                    <div class="block-menu">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

